# 全局变量配置文件

cacheTime = 7200000 #缓存校验时间
baseURL = "http://192.168.1.108:8181"
webURL = "http://192.168.1.108:8383"

# 提示信息配置文件
LoadingTimeOut = "请求超时"
LoadingFailure = "请求失败"

loginUrl = "/login.jsp"
logoutUrl = "/logout"


# 全局table分页的配置
[PageConfig]
  sizes = [10, 20, 30, 40]
  limit = 10
  page = 1
  start = 0
